# 2x2x2 Rubiks cube

# Bump & Auerbach 
# http://sporadic.stanford.edu/bump/match/morepolished.pdf

# G = (Z/3)^5 ⋊ PGL_2(5) where (Z/3)^5 ⊂ (Z/3)^6 is the linear code with Hamming weight 0.
# order(G) = 3^5 * 120 = 29160


# Generated by involutions s.t. diameter(Cayley graph) = 17